spring:
  datasource:
    druid:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      max-active: 5
      initial-size: 1
      keep-alive: true
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
    enabled: true
    cache: false
    check-template-location: true
mybatis:
  mapper-locations: classpath:mapper/**.xml
logging:
  level:
   #com.web.freemarker.demo.mapper: debug
   com.web.freemarker.demo.*: debug
qiniu:
  access-key:
  secret-key:
  url:
  bucket: demo
